//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IliaCodeTest.Borders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IliaCodeTest.Borders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao Adicionar consumidor..
        /// </summary>
        public static string UnexpectedErrorAddConsumer {
            get {
                return ResourceManager.GetString("UnexpectedErrorAddConsumer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao Obter Consumidores..
        /// </summary>
        public static string UnexpectedErrorGetConsumer {
            get {
                return ResourceManager.GetString("UnexpectedErrorGetConsumer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro Inesperado ao Obter Pedidos..
        /// </summary>
        public static string UnexpectedErrorGetOrders {
            get {
                return ResourceManager.GetString("UnexpectedErrorGetOrders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro Inesperado ao Registrar Novo Pedido..
        /// </summary>
        public static string UnexpectedErrorRegisterNewOrders {
            get {
                return ResourceManager.GetString("UnexpectedErrorRegisterNewOrders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao Atualizar Status Pedido. .
        /// </summary>
        public static string UnexpectedErrorUpdateOrderStatus {
            get {
                return ResourceManager.GetString("UnexpectedErrorUpdateOrderStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ser informado..
        /// </summary>
        public static string ValidateCPFMustBeInformed {
            get {
                return ResourceManager.GetString("ValidateCPFMustBeInformed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Email deve ser um Email Válido..
        /// </summary>
        public static string ValidateEmailIsValid {
            get {
                return ResourceManager.GetString("ValidateEmailIsValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Email deve ser informado..
        /// </summary>
        public static string ValidateEmailMustBeInformed {
            get {
                return ResourceManager.GetString("ValidateEmailMustBeInformed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Cpf deve ser Válido..
        /// </summary>
        public static string ValidateMainDocumentIsValid {
            get {
                return ResourceManager.GetString("ValidateMainDocumentIsValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Email e/ou CPF apresentado já foram cadastrados na base, favor verificar..
        /// </summary>
        public static string ValidateUniqueCPFandEmail {
            get {
                return ResourceManager.GetString("ValidateUniqueCPFandEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de Usuário deve ser informado..
        /// </summary>
        public static string ValidateUserNameMustBeInformed {
            get {
                return ResourceManager.GetString("ValidateUserNameMustBeInformed", resourceCulture);
            }
        }
    }
}
